# Generated by Django 4.2.27 on 2026-01-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('home_address', models.CharField(max_length=255)),
                ('home_lat', models.FloatField(blank=True, null=True)),
                ('home_lng', models.FloatField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('max_distance_km', 'Max distance (km)'), ('weekend_allowed', 'Weekend allowed'), ('max_long_trips_per_month', 'Max long trips per month'), ('preferred_weekdays', 'Preferred weekdays')], max_length=50)),
                ('rule_value', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='trainers.trainer')),
            ],
        ),
    ]
