# Generated by Django 4.2.27 on 2026-01-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerskill',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_skills', to='trainings.trainingtype'),
        ),
        migrations.AddField(
            model_name='trainerrule',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='trainers.trainer'),
        ),
        migrations.AddConstraint(
            model_name='trainerskill',
            constraint=models.UniqueConstraint(fields=('trainer', 'training_type'), name='unique_trainer_skill'),
        ),
        migrations.AddIndex(
            model_name='trainerrule',
            index=models.Index(fields=['trainer', 'rule_type'], name='trainers_tr_trainer_137253_idx'),
        ),
    ]
