# Generated by Django 4.2.27 on 2026-01-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='base_price',
        ),
        migrations.AddField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='hourly rate (CZK)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='travel_rate_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='travel rate (CZK/km)'),
        ),
    ]
