# Generated by Django 4.2.27 on 2026-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('provider', models.CharField(default='nominatim', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
