# Generated by Django 4.2.27 on 2026-01-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting for trainer'), ('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('assignment_reason', models.TextField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to='trainers.trainer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to='trainings.trainingtype')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['start_datetime'], name='trainings_t_start_d_01c571_idx'), models.Index(fields=['status'], name='trainings_t_status_8ebfec_idx'), models.Index(fields=['assigned_trainer'], name='trainings_t_assigne_6cd623_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='training_end_after_start'),
        ),
    ]
