# Generated by Django 4.2.27 on 2026-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='objednavatel'),
        ),
    ]
